### ISSUE TITLE
Error:topanga after using Delectra

### ISSUE THREAD

**Issue by jacc** [KirovAir/delectra#9]
Hey,

I use SemiRestore + Delectra last night, then reset all content and settings. After using it, Rc1.04 doesn’t work. I was able to use Beta7 to get jailbroken, but even after following a lot of guides to fix the error, it still gives me the error. Help?

**Comment by jabesmartinez** [comment]
Download Electra 1.01 and then jailbreak it should fix it if it give you the message reboot device an try again takes a few tries believe me

**Comment by sytler** [comment]
also getting topanga error even tho I didnt have installed any of those shitty topanga/liberios jailbreaks

**Comment by KirovAir** [comment]
It has to do with some remaining files that the latest electra checks. I can't see those though since the last versions are closed source.
This is the last list I could compile from source of which files to check:
https://gist.github.com/KirovAir/a84afe1c8e75309abd731893ed5e1e37
Taken from:
https://github.com/coolstar/electra/blob/cydia/electra/the%20fun%20part/utilities/topangadetect.m

But these are already in the delectra script, so there could be a file which was not deleted properly because it was in use, or simply extra checks to the latest electra. (I'd say option 1 is more plausible)

**Comment by jacc** [comment]
I fixed it by installing Beta 7, running unjailbreak.sh, then rejailbreaking.

**Comment by sytler** [comment]
sry forgot to mention after some days, I did rejailbreak with beta electra without tweaks and run delectra again

**Comment by remihacker5** [comment]
to fix the error:topanga, download the topanga remover app (you may need to download the ipa file and impact it) and then click the "remove jailbreak" button and then reboot it. that should work.

**Comment by jacc** [comment]
this is so old lmfao
